[package]
name = "smush_materials"
version = "0.1.0"
edition = "2024"

[dependencies]
smush_shader = { path = "../smush_shader" }
clap = { version = "4.5.7", features = ["derive"] }
globwalk = "0.9.1"
rayon = "1.5.1"
xmltree = { version = "0.10.3", features = ["attribute-order"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.0"
xmb_lib = { git = "https://github.com/ultimate-research/xmb_lib", rev = "86470a7" }
ssbh_lib = { git = "https://github.com/ultimate-research/ssbh_lib", rev = "35dedc4" }
ssbh_data = { git = "https://github.com/ultimate-research/ssbh_lib", features=["serde"], rev = "35dedc4" }
glsl-lang = "0.8.0"
indoc = "2.0"
xc3_shader = { workspace = true, features = ["glsl"] }
indexmap.workspace = true
smol_str.workspace = true
log.workspace = true
simple_logger = "5.2.0"
anyhow = "1.0"

[dev-dependencies]
pretty_assertions = "1.4.1"
